### ISSUE TITLE
Show the timestamp in HH:MM:SS

### ISSUE THREAD

**Issue by nmpereira** [nmpereira/time-share-v2#13]
## What
Convert the timestamp from seconds to HH:MM:SS

## How
Create a reusable function that converts seconds into HH:MM:SS.

Cases:
1.  00:00
2. 00:05
3. 00:59
4. 25:59
5. 02:59:59
6. 9999:59:59

## Testing
- Write jest tests to verify the timestamps

**Comment by intelagense** [comment]
I'm in

**Comment by riddlew** [comment]
👆 I'm in

**Comment by nmpereira** [comment]
Please add jest tests for the `formatTimestamp` function. You can resync the code from main https://github.com/nmpereira/time-share-v2/tree/main and start working on the jest tests. There is an example jest test that I already created so you can get started on it.
